name: "Update Bot"
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: '0 9,21 * * *'
      
jobs:
  update-data:
    name: Update Bot
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v2
      - name: "Setup - Install Packages"
        run: |
          install.packages('telegram.bot')
        shell: Rscript {0}
      - name: "Check for updates"
        run: Rscript 'bot_update.R'
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Routine Update
